### PR TITLE
CNAME file support

### PR DESCRIPTION
**Pull request by santacruz123**
https://help.github.com/articles/adding-a-cname-file-to-your-repository

### CODE REVIEW

**Comment by mplewis** [comment]
Is this PR still ready for merging?

**Comment by Robdel12** [comment]
+1, I'd really like to use this and would rather not fork and publish it myself :P

**Comment by shinnn** [comment]
Thanks for the PR but I don't think it's not really needed. Use [gulp-file](https://github.com/alexmingoia/gulp-file) or else in this case.

**Comment by Robdel12** [comment]
I disagree. This would be a very nice abstraction for this plugin. Instead of everyone having to add a custom way of getting their `CNAME` file into the gh-pages brach, it should be supported in this plugin.

**Comment by shinnn** [comment]
According to [the plugin guideline](https://github.com/gulpjs/gulp/blob/20774ccfae315d14e693623c2768a9e2ca20af20/docs/writing-a-plugin/guidelines.md), 

> Your plugin shouldn't do things that other plugins are responsible for

**Comment by mplewis** [comment]
If anyone else wants to know how they can add a `CNAME` file to the middle of their build, I did what @shinnn suggested: I [added a file to the pipe using gulp-file](https://github.com/mplewis/obsessive-react-reflux-example/blob/a52fc9c2553ba335491ed38ab4712a784da1a5ec/gulpfile.js#L104).

Thanks for supporting gulp-gh-pages @shinnn!

**Comment by shinnn** [comment]
@mplewis Yeah, your example is just what I meant.

**Pull request closed without merging**
