### PR TITLE
Update gift dependency

### PR DESCRIPTION
**Pull request by tekd**
This updates the gift dependency here:
https://david-dm.org/shinnn/gulp-gh-pages#info=devDependencies
which should remedy issue #116.

### CODE REVIEW

**Comment by DavidLemayian** [comment]
Awesome stuff! Watching this for merge. :)

**Comment by ghost** [comment]
Also waiting for this merge. @shinnn how can we help?

**Comment by lidianhao123** [comment]
Looking forward to merge this PR. @shinnn

**Comment by osharpe** [comment]
When is this likely to be merged? @shinnn

**Comment by atesgoral** [comment]
As an interim solution, I'm using @tekd's fork...

**Comment by buy** [comment]
bumping this up ... got the same error

**Comment by serbanghita** [comment]
I can confirm this is working by setting `"gulp-gh-pages": "git@github.com:tekd/gulp-gh-pages.git#update-dependency",` in your `package.json`.

I think it's also worth investigating why the coverage dropped just by updating a 3rd party dependency.

SHIP IT! 🚢

**Comment by colinthornton** [comment]
I'm also using @tekd's fork with no issues.

**Comment by melanieseltzer** [comment]
Works great! @shinnn any news on this?

**Comment by matthewcpaul** [comment]
Any update on this? I'm experiencing the same problem when trying to run `gulp deploy`.

@tekd @serbanghita I can't use `"gulp-gh-pages": "git@github.com:tekd/gulp-gh-pages.git#update-dependency",` either, because I get a permission denied error. Any ideas?

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/tekd/gulp-gh-pages.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by tekd** [comment]
Hey @matthewcpaul, any chance it's an [ssh set up](https://help.github.com/articles/connecting-to-github-with-ssh/) issue? Can you see if this works instead: `"gulp-gh-pages”: “tekd/gulp-gh-pages"`

**Comment by matthewcpaul** [comment]
@tekd I got a different error this time: It looks like this is on my end; do you have any idea for a fix?
```
Error in plugin 'gulp-gh-pages'
Message:
    Command failed: git pull  
From https://github.com/matthewcpaul/gulp-jekyll
 + ff482bb...e705838 gh-pages   -> origin/gh-pages  (forced update)
   abce6c1..81694d7  master     -> origin/master
fatal: refusing to merge unrelated histories

Details:
    killed: false
    code: 128
    signal: null
    cmd: git pull  
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by dpagini** [comment]
I don't quite remember all my context for this issue, but I ran into this problem as well (and flagged this issue).

I took this PR branch and forked it to my own copy (sorry, just wanted to make sure it persisted) and pointed my package.json file to that private repo/branch via the below.

```json
  "gulp-gh-pages": "git+ssh://git@github.com/private-repo/gulp-gh-pages.git#update-dependency",
```
_where "private-repo" is a placeholder_  =)

**Comment by willianjusten** [comment]
I had the same issues, so I decided to update the deppendency and create a npm package. It's available [gulp-gh-pages-will](https://www.npmjs.com/package/gulp-gh-pages-will).

**Pull request merged**
